version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
    expose:
      - ${MYSQLDB_DOCKER_PORT}

  app:
    depends_on:
      - mysqldb
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
      - "9229:9229"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=${MYSQLDB_USER}
      - DB_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DB_DBNAME=${MYSQLDB_DATABASE}
      - DB_PORT=${MYSQLDB_DOCKER_PORT}
      - ENVIRONMENT=production
    stdin_open: true
    expose:
      - "8080"
    tty: true
    volumes:
      - ./:/usr/src/app
      - ./nodemon.json:/usr/src/app/nodemon.json
volumes:
  db: